# Generated by Django 2.2.4 on 2019-08-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190809_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculos',
            name='proprietario',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
