# Generated by Django 2.2.4 on 2019-08-09 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_veiculos_proprietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculos',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pessoa'),
        ),
    ]
